# Generated by Django 5.1.6 on 2025-03-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_book_file_bookfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfile',
            name='author',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'Author'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
