# Generated by Django 5.1.6 on 2025-03-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bookfile_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublishRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_requests', to='myapp.book')),
                ('publisher', models.ForeignKey(limit_choices_to={'role': 'Publisher'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
